language: node_js

node_js:
- 7.8.0

before_install:
- openssl aes-256-cbc -K $encrypted_675be29fedeb_key -iv $encrypted_675be29fedeb_iv
  -in id_rsa.enc -out id_rsa -d

install:
- npm i -g yarn && yarn

before_script:
- yarn run production

script:
  - echo All tests pass, yay!

after_sucess:
- yarn run gh-pages-travis

env:
  global:
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="build"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="travis-deployment"
  - GIT_EMAIL="deploy@travis-ci.org"

branches:
  except:
  - gh-pages
